import Head from "next/head";
import Link from "next/link";
import { FaBox } from "react-icons/fa";
import { Container, ProductList, RootLayout } from "~/components";
import { Button } from "~/components/ui/button";
import { type NextPageWithLayout } from "~/types";

const products = [
  {
    id: "1",
    category: "Camera",
    name: "Sony FX3",
    price: "$3,999.00",
    images: [""],
  },
  {
    id: "2",
    category: "Camera",
    name: "Sony A7S III",
    price: "$3,499.00",
    images: [""],
  },
  {
    id: "3",
    category: "Camera",
    name: "Sony A7C",
    price: "$1,599.00",
    images: [""],
  },
  {
    id: "4",
    category: "Camera",
    name: "Sony A7 IV",
    price: "$2,399.00",
    images: [""],
  },
  {
    id: "5",
    category: "Camera",
    name: "Sony A7R III",
    price: "$2,499.00",
    images: [""],
  },
  {
    id: "6",
    category: "Camera",
    name: "Sony A7R V",
    price: "$3,899.00",
    images: [""],
  },
  {
    id: "7",
    category: "Camera",
    name: "Sony A6700",
    price: "$1,799.00",
    images: [""],
  },
  {
    id: "8",
    category: "Camera",
    name: "Sony AZV-E10",
    price: "$699.00",
    images: [""],
  },
];

const Home: NextPageWithLayout = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Container>
          <div className="space-y-4 pb-10">
            <div className="p-4 sm:p-6 lg:p-8 rounded-lg overflow-hidden">
              <div
                style={{ backgroundImage: `url(/images/pexels-cottonbro-studio-6069528.jpg)` }}
                className="rounded-lg relative md:aspect-[2.4/1] overflow-hidden bg-cover aspect-square bg-center"
              >
                <div className="h-full w-full flex flex-col justify-center items-center text-center gap-y-8">
                  <div className="font-bold text-3xl sm:text-5xl lg:text-6xl sm:max-w-xl max-w-xs text-black dark:text-white bg-secondary/75 p-4 rounded-lg">
                    Sell Items You Don't Need Anymore
                    <div className="text-sm my-4">Turn Your Unused Items into Quick Cash with Easy Local Selling.</div>
                    <Link href="/sell">
                      <Button size="lg" className="w-full py-6 text-xl">
                        <FaBox className="mr-2" /> Start Selling
                      </Button>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
            <div className="px-4 sm:px-6 lg:px-8 text-xl font-bold ">Available for Sale Near You</div>
            <div className="flex flex-col gap-y-8 px-4 sm:px-6 lg:px-8">
              <ProductList items={products} />
            </div>
          </div>
        </Container>
      </main>
    </>
  );
}

Home.getLayout = (page) => {
  return <RootLayout>{page}</RootLayout>
}

export default Home
