import Head from "next/head";
import Link from "next/link";
import { FaBox } from "react-icons/fa";
import { Container, ProductList, RootLayout } from "~/components";
import { Button } from "~/components/ui/button";
import { type NextPageWithLayout } from "~/types";
import { api } from "~/utils/api";

const Home: NextPageWithLayout = () => {
  const products = api.product.listAll.useQuery()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <div className="space-y-4 pb-10">
          <div className="p-4 sm:p-6 lg:p-8 rounded-lg overflow-hidden">
            <div
              style={{ backgroundImage: `url(/images/pexels-cottonbro-studio-6069528.jpg)` }}
              className="rounded-lg relative md:aspect-[2.4/1] overflow-hidden bg-cover aspect-square bg-center"
            >
              <div className="h-full w-full flex flex-col justify-center items-center text-center gap-y-8">
                <div className="font-bold text-3xl sm:text-5xl lg:text-6xl sm:max-w-xl max-w-xs text-black dark:text-white bg-secondary/75 p-4 rounded-lg">
                  Sell Items You Don't Need Anymore
                  <div className="text-sm my-4">Turn Your Unused Items into Quick Cash with Easy Local Selling.</div>
                  <Link href="/sell">
                    <Button size="lg" className="w-full py-6 text-xl">
                      <FaBox className="mr-2" /> Start Selling
                    </Button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
          <div className="px-4 sm:px-6 lg:px-8 text-xl font-bold ">Available for Sale Near You</div>
          <div className="flex flex-col gap-y-8 px-4 sm:px-6 lg:px-8">
            {
              products.data &&
              <ProductList items={products?.data} />
            }
          </div>
        </div>
      </Container>
    </>
  );
}

Home.getLayout = (page) => {
  return <RootLayout>{page}</RootLayout>
}

export default Home
